<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>

<body>
    <div class="container mt-5">
        <?php


        if (isset($_SESSION['firstname']) && isset($_SESSION['lastname'])) {
        ?>
            <h1 class="text-center mb-4">Bienvenue <?= "{$_SESSION['firstname']} {$_SESSION['lastname']} !" ?></h1>
        <?php
        } else {

            echo "Utilisateur non connecté sur le site";
        }
        ?>


        <div class="d-flex justify-content-center gap-3">
            <a href="index.php?route=inscription" class="btn btn-primary">Inscription</a>
            <a href="index.php?route=connexion" class="btn btn-secondary">Connexion</a>
            <a href="logout.php" class="btn btn-warning">Deconnexion</a>
        </div>
    </div>

</body>

</html>