<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>


    <?php

    if ($template === null || $template === "homepage") {
        require "home.phtml";
    } else if ($template === "inscription") {
        require "register.phtml";
    } else if ($template === "connexion") {
        require "login.phtml";
    }

    ?>



</body>

</html>