<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>

<body id="choice-<?php echo $color; ?>" data-event="<?= $eventNumber; ?>">
    <main>
        <section>
            <h2><?= $choiceShortSentence ?></h2>
            <div>
                <form method="get" action="choices.php">
                    <input type="hidden" name="eventNumber" value="<?php echo $eventNumber; ?>" />
                    <?php foreach ($choices as $key => $choice) { ?>
                        <div>
                            <input type="radio" id="choice-<?php echo $key; ?>" name="choice" value="<?php echo $key ?>">
                            <label for="choice-<?php echo $key ?>"><?php echo $choice; ?></label>
                        </div>
                    <?php } ?>
                    <input type="submit" value="Valider le choix" />
            </div>
            </form>
            </div>
        </section>
        <section>
            <section>
                <img id=<?= $imageId ?> src=<?= $eventImage ?> />
                <h1><?= $eventDescription ?></h1>
            </section>
        </section>
    </main>
    <audio id="celebrationSound" src="assets/internationale8bit.mp3" preload="auto"></audio>
    <script type="application/javascript" src="assets/js/index.js"></script>
</body>

</html>