<form method="POST" action="index.php?route=check_create_user">
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email">

    </div>
    <div class="mb-3">
        <label for="firstName" class="form-label">Prénom</label>
        <input type="text" class="form-control" id="firstName" name="firstName">

    </div>
    <div class="mb-3">
        <label for="lastName" class="form-label">Nom</label>
        <input type="text" class="form-control" id="lastName" name="lastName">

    </div>


    <button type="submit" name="validate" class="btn btn-primary">Submit</button>
</form>