<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercice Routeur MVC</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <!-- <header class="bg-dark text-white p-3">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="index.php">Exercice MVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=a-propos">À propos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=contact">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header> -->

    <!-- <div class="container mt-5">
        <?php
        if ($route === "home") {
            require "templates/home.phtml";
        } elseif ($route === "about") {
            require "templates/about.phtml";
        } elseif ($route === "contact") {
            require "templates/contact.phtml";
        } elseif ($route === "notFound") {
            require "templates/notFound.phtml";
        }
        ?>
    </div> -->



</body>

</html>